name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build executable for release
        run: swift build -c release --arch arm64 --arch x86_64 --product create-project-plist
      - name: Compress archive
        run: tar -czf create-project-plist.v${{ github.ref_name }}.tar.gz -C .build/apple/Products/Release create-project-plist
      - name: Get latest release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v2
        with:
          command: query
          version: latest
      - name: Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.query-release-info.outputs.release-notes }}
          files: create-project-plist.v${{ github.ref_name }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: create-project-plist
          homebrew-tap: astzweig/homebrew-formulae
          download-url: ${{ fromJSON(steps.create-release.outputs.assets)[0].browser_download_url }}
          commit-message: |
            Bump {{formulaName}} {{version}}

            Created by GitHub Workflow of ${{ github.repository }}.
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_FORMULAE_TOKEN }}
